### ISSUE TITLE
run fails with "SyntaxError: invalid syntax"

### ISSUE THREAD

**Issue by jtmoon79** [rsnitsch/py3createtorrent#4]
Running `py3createtorrent` results in immediate `SyntaxError`.

```
‣ py3createtorrent
Traceback (most recent call last):
  File "/usr/local/bin/py3createtorrent", line 5, in <module>
    from py3createtorrent import main
  File "/usr/local/lib/python3.5/dist-packages/py3createtorrent.py", line 339
    parts: List[str] = []
         ^
SyntaxError: invalid syntax
```

Using python _3.5.3_, `py3createtorrent` version _1.0.0.dev2_. Installed using `python -m pip install py3createtorrent`.

**Comment by rsnitsch** [comment]
Thank you for reporting this issue!

I released a new version 1.0.0.dev3 where this should be fixed (the fix is in commit: https://github.com/rsnitsch/py3createtorrent/commit/b342503e54fc5c6ade620f46c5bc674f0710c886).

Please try again after upgrading to this latest version: `python -m pip install --upgrade py3createtorrent`.

**Comment by rsnitsch** [comment]
No feedback, therefore closing the issue. I assume the fix has been successful.

**Comment by jtmoon79** [comment]
> No feedback, therefore closing the issue. I assume the fix has been successful.

Works! :-)

```
‣ python --version
Python 3.5.3

‣ python -m pip install py3createtorrent
DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.
Collecting py3createtorrent
  Downloading py3createtorrent-1.0.0.dev4-py3-none-any.whl (12 kB)
Collecting bencode.py
  Downloading bencode.py-4.0.0-py2.py3-none-any.whl (18 kB)
Installing collected packages: bencode.py, py3createtorrent
Successfully installed bencode.py-4.0.0 py3createtorrent-1.0.0.dev4

‣ py3createtorrent
usage: py3createtorrent [-h] [-p PIECE_LENGTH] [-P] [-c COMMENT] [-s SOURCE]
                        [-f] [-v] [-q] [-o PATH] [-e PATH]
                        [--exclude-pattern REGEXP]
                        [--exclude-pattern-ci REGEXP] [-d TIMESTAMP] [-n NAME]
                        [--md5] [-t TRACKER_URL] [--node HOST,PORT]
                        [--webseed WEBSEED_URL]
                        path
py3createtorrent: error: the following arguments are required: path
```
